### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by timmykill** [kenorb-contrib/tgl#20]
Hi, I'm trying to package this repo for voild linux.
They don't allow git packages, so I would like to have a release that i can use.
The current release doesn't contain the `tl_parser` subdir, so it wont compile.
It's also very old.
Could you make another release please?

**Comment by kenorb** [comment]
I did it, let me know if that helped.
https://github.com/kenorb-contrib/tgl/releases

**Comment by timmykill** [comment]
It did, but i would need a new release in the main repo too (tg), since the different versions wont compile together.
Thanks for the fast response.

**Comment by kenorb** [comment]
> It did, but i would need a new release in the main repo too (tg).

Done.

**Comment by timmykill** [comment]
Thanks, everything works.
Here the pull request if you want to see if they merge it in the main repo
https://github.com/void-linux/void-packages/pull/18693
